### ISSUE TITLE
MediаInfo throwing a fatal 

### ISSUE THREAD

**Issue by rromanchuk** [awslabs/video-on-demand-on-aws#16]
```
2018-10-17T05:19:55.755Z 547088fc-235d-497e-9a1c-1cebb8f4ce9c TypeError: result.Mediainfo.File.track.forEach is not a function
at $xmlParserInstance.parseString (/var/task/lib/mediaInfoCommand.js:82:35)
at Parser.<anonymous> (/var/task/node_modules/xml2js/lib/parser.js:303:18)
at emitOne (events.js:96:13)
at Parser.emit (events.js:188:7)
at Object.onclosetag (/var/task/node_modules/xml2js/lib/parser.js:261:26)
at emit (/var/task/node_modules/xml2js/node_modules/sax/lib/sax.js:624:35)
at emitNode (/var/task/node_modules/xml2js/node_modules/sax/lib/sax.js:629:5)
at closeTag (/var/task/node_modules/xml2js/node_modules/sax/lib/sax.js:889:7)
at Object.write (/var/task/node_modules/xml2js/node_modules/sax/lib/sax.js:1436:13)
at Parser.exports.Parser.Parser.parseString (/var/task/node_modules/xml2js/lib/parser.js:322:31)
```

I'm still trying to understand what's going on here, but I think it's from a corrupted source video. When pulling the source video, it's not playable, and various desktop video players aren't able to inspect the video. 

This error would make sense, but it's a misleading error, there should probably be a validation check that this collection exists before trying to iterate with `forEach`

**Comment by rromanchuk** [comment]
@tomnight at first i thought it was something more complicated, but when i went back to investigate, it was just a bogus upload. I haven't had any issues with mediaInfo under normal circumstances, but i guess catching/validating would be helpful. That stack trace sound a lot more menacing than it is.
