### ISSUE TITLE
Python throws exception when ./build-s3-dist.sh is run

### ISSUE THREAD

**Issue by neeraj-wadhwa-cc** [awslabs/video-on-demand-on-aws#66]
Hi,

When I run `./build-s3-dist.sh <bucket_name> video-on-demand-on-aws v5.0.0-custom`, Python3.7 throws the error pasted below:

`Installing collected packages: urllib3, six, python-dateutil, jmespath, docutils, botocore, s3transfer, boto3
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
Command failed with exit code: 2
`
This occurs when creating a deployment package for mediainfo.

**Comment by dscpinheiro** [comment]
Hi @neeraj-wadhwa-cc,

Are you running this command on MacOS and if so, did you install Python via Homebrew?

If that's the case, could you follow the workaround suggested on this StackOverflow answer ( https://stackoverflow.com/a/44728772) and see if the problem still happens?

**Comment by neeraj-wadhwa-cc** [comment]
Hi @dscpinheiro,

I'm using Elementary OS (Ubuntu-based system).

**Comment by dscpinheiro** [comment]
Unfortunately I don't have access to Elementary OS to test it.

Would it be possible to run these commands in an EC2 instance? It should work with any of the AMIs that Lambda uses (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), since that's the OS the solution will eventually use.

**Comment by aassadza** [comment]
We are closing this issue, but please feel free to open the issue again if you need any other support.
